### PR TITLE
replace deep object undefined properties

### PR DESCRIPTION
**Pull request by yadimon**

### CODE REVIEW

**Comment by Istador** [comment]
Hello, thank you for your contribution.

Can you please provide an example input (or even a [test case](https://github.com/Istador/lodash-es-merge-undefined/blob/57cdb1bdc8c79aa5b94f4eef87298b17dd617b73/index.test.js)) that isn't working correctly currently?

**Comment by yadimon** [comment]
sorry was too fast from my side :)

example:

```
merge( {a: 'any'}, {a:  {a_a: undefined}} )

// result:
// {a: {} }

// expected
// { a: {a_a: undefined} }
```

**Comment by yadimon** [comment]
added some tests and npm fix.

**Comment by Istador** [comment]
Release [v1.0.3](https://github.com/Istador/lodash-es-merge-undefined/releases/tag/1.0.3)

**Pull request merged**
